// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static String _val(String key) {
    return String.fromEnvironment(key);
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: _val('FIREBASE_API_KEY_WEB'),
    appId: _val('FIREBASE_APP_ID_WEB'),
    messagingSenderId: _val('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _val('FIREBASE_PROJECT_ID'),
    authDomain: _val('FIREBASE_AUTH_DOMAIN'),
    storageBucket: _val('FIREBASE_STORAGE_BUCKET'),
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: _val('FIREBASE_API_KEY_ANDROID'),
    appId: _val('FIREBASE_APP_ID_ANDROID'),
    messagingSenderId: _val('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _val('FIREBASE_PROJECT_ID'),
    storageBucket: _val('FIREBASE_STORAGE_BUCKET'),
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: _val('FIREBASE_API_KEY_IOS'),
    appId: _val('FIREBASE_APP_ID_IOS'),
    messagingSenderId: _val('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _val('FIREBASE_PROJECT_ID'),
    storageBucket: _val('FIREBASE_STORAGE_BUCKET'),
    iosBundleId: _val('FIREBASE_IOS_BUNDLE_ID'),
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: _val('FIREBASE_API_KEY_IOS'),
    appId: _val('FIREBASE_APP_ID_IOS'),
    messagingSenderId: _val('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _val('FIREBASE_PROJECT_ID'),
    storageBucket: _val('FIREBASE_STORAGE_BUCKET'),
    iosBundleId: _val('FIREBASE_IOS_BUNDLE_ID'),
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: _val('FIREBASE_API_KEY_WINDOWS'),
    appId: _val('FIREBASE_APP_ID_WINDOWS'),
    messagingSenderId: _val('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _val('FIREBASE_PROJECT_ID'),
    authDomain: _val('FIREBASE_AUTH_DOMAIN'),
    storageBucket: _val('FIREBASE_STORAGE_BUCKET'),
  );
}
