// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  // Security Note: These are placeholder values.
  // For a production app, the real keys would be managed via environment variables.
  // The goal here is to showcase the app's structure and features.

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'WEB_API_KEY_PLACEHOLDER',
    appId: 'WEB_APP_ID_PLACEHOLDER',
    messagingSenderId: 'SENDER_ID_PLACEHOLDER',
    projectId: 'DIWAN_ANKARA_PROJECT_ID',
    authDomain: 'diwan-ankara.firebaseapp.com',
    storageBucket: 'diwan-ankara.firebasestorage.app',
  );

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'ANDROID_API_KEY_PLACEHOLDER',
    appId: 'ANDROID_APP_ID_PLACEHOLDER',
    messagingSenderId: 'SENDER_ID_PLACEHOLDER',
    projectId: 'DIWAN_ANKARA_PROJECT_ID',
    storageBucket: 'diwan-ankara.firebasestorage.app',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'IOS_API_KEY_PLACEHOLDER',
    appId: 'IOS_APP_ID_PLACEHOLDER',
    messagingSenderId: 'SENDER_ID_PLACEHOLDER',
    projectId: 'DIWAN_ANKARA_PROJECT_ID',
    storageBucket: 'diwan-ankara.firebasestorage.app',
    iosBundleId: 'com.diwan.ankara.app',
  );

  static FirebaseOptions macos = const FirebaseOptions(
    apiKey: 'IOS_API_KEY_PLACEHOLDER',
    appId: 'IOS_APP_ID_PLACEHOLDER',
    messagingSenderId: 'SENDER_ID_PLACEHOLDER',
    projectId: 'DIWAN_ANKARA_PROJECT_ID',
    storageBucket: 'diwan-ankara.firebasestorage.app',
    iosBundleId: 'com.diwan.ankara.app',
  );

  static FirebaseOptions windows = const FirebaseOptions(
    apiKey: 'WINDOWS_API_KEY_PLACEHOLDER',
    appId: 'WINDOWS_APP_ID_PLACEHOLDER',
    messagingSenderId: 'SENDER_ID_PLACEHOLDER',
    projectId: 'DIWAN_ANKARA_PROJECT_ID',
    authDomain: 'diwan-ankara.firebaseapp.com',
    storageBucket: 'diwan-ankara.firebasestorage.app',
  );
}